name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: print commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: print commit messages
        env:
          COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message)) }}
        run: echo "$COMMIT_MESSAGES"
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: ${{ github.event_name == 'push' }}
      - run: flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Bump version and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: true
          COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message)) }}
        if: ${{ github.event_name == 'push' && !contains("my long array","#skip") }} 
        uses: anothrNick/github-tag-action@1.36.0

