name: Print event info pipeline

on:
  push

jobs:
  print:
    runs-on: ubuntu-20.04
    steps:
      - name: print event 
        run: echo "${{ toJson(github.event) }}"
      - name: print commits 
        run: echo "${{ toJson(github.event.commits) }}"
      - name: print commit messages
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: echo "COMMIT_MESSAGES=$COMMIT_MESSAGES" >> $GITHUB_ENV